redis:
  image: redis:3.0.7
  ports:
    - "6379:6379"
worker:
  build: .
  dockerfile: Dockerfile-worker
  links:
    - redis:redis
server:
  build: .
  dockerfile: Dockerfile-server
  links:
    - redis:redis
  ports:
    - "8080:8080"
webapp:
  build: .
  dockerfile: Dockerfile-webapp
  ports:
    - "9000:9000"
websocket:
  build: .
  dockerfile: Dockerfile-ws
  links:
    - redis:redis
  ports:
    - "8081:8081"
